services:
  google-drive-api-service:
    container_name: google-drive-api-service
    environment:
      DB_PASSWORD: postgres
      DB_USER: postgres
    ports:
      - "8085:8080"

volumes:
  postgres_data: