spring:
  application:
    name: GoogleDriveApiService
  r2dbc:
    url: r2dbc:pool:postgresql://postgres:postgres@localhost:5432/google_drive_api
    password: postgres
    username: postgres
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081
  netty:
    connection-timeout: 20000
  max-http-request-header-size: 65536