spring:
  application:
    name: GoogleDriveApiService
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:google_drive_api}${DB_URL_PARAM}
    password: ${DB_PASSWORD:postgres}
    username: ${DB_USER:postgres}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  netty:
    connection-timeout: 20000
  max-http-request-header-size: 65536

  # DB_URL_PARAM: ?ssl=true